version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/working
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install .[all] --user
      - run: pip3 install -U pytest pytest-cov --user
      - run: cd SeismicMesh && c++ -O3 -Wall -shared -std=c++11 -fPIC -Wl,-undefined,dynamic_lookup `python3 -m pybind11 --includes` FastHJ.cpp -o FastHJ`python3-config --extension-suffix` && cd .. && pytest --cov SeismicMesh
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
