version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/working
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: sudo apt install -y cmake
      - run: git clone https://github.com/CGAL/cgal.git && tar xf CGAL-5.0.2.tar.xz && cd CGAL-5.0.2/ && mkdir build && cd build && cmake . && sudo make install
      - run: sudo apt install -y libhdf5-dev
      - run: sudo apt install -y mpich
      - run: git submodule sync
      - run: git submodule update --init
      - run: pip3 install .[all] --user
      - run: pip3 install -U pytest pytest-cov --user
      - run:
          command: pytest
          working_directory: tests/
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
